<?php


namespace frontend\controllers;

use yii;
use yii\web\Controller;

class BaseController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->view->theme->pathMap=['@views' => '@themes/basic/views'];
    }
}